---
# tasks file for ansible-role-collectd
#

  - name: install EPEL
    yum: name=epel-release state=present

  - name: install collectd
    yum: name=collectd state=present

  - name: install collectd_plugin_packages
    yum: name={{ item }} state=present
    with_items: collectd_plugin_packages

  - name: template in collectd.d/collectd.conf
    template: src=collectd.conf.j2 dest={{ collectd_conf_dir }}/collectd.conf owner=root mode=0644 backup=no
    register: collectd_config

  - name: install the ipmitool.sh on non-virtualized hosts
    get_url: url=https://raw.githubusercontent.com/lunetics/collectd-plugins/32d751ed913b1e1d84bf78a4848648fb63379689/ipmitool/ipmitool.sh dest=/usr/local/bin/ipmitool.sh owner=nobody group=nobody mode=0755 backup=yes
    when: ansible_virtualization_type != "kvm"

  - name: enable and start collectd
    service: name=collectd state=started enabled=yes

  - name: restart collectd on configchange
    service: name=collectd state=restarted
    when: collectd_config.changed
