---
# tasks file for ansible-role-collectd
#

  - name: install EPEL
    yum: name=epel-release state=present

  - name: install collectd
    yum: name=collectd state=present

  - name: install collectd_plugin_packages
    yum: name={{ item }} state=present
    with_items: "{{ collectd_plugin_packages }}"

  - name: template in collectd.d/collectd.conf
    template: src=collectd.conf.j2 dest={{ collectd_conf_dir }}/collectd.conf owner=root mode=0644 backup=no
    register: collectd_config

  - name: install the ipmitool.sh on non guest hosts
    get_url: owner=nobody group=nobody mode=0755 backup=yes 
             url=https://raw.githubusercontent.com/lunetics/collectd-plugins/32d751ed913b1e1d84bf78a4848648fb63379689/ipmitool/ipmitool.sh 
             dest=/usr/local/bin/ipmitool.sh
             force={{ collectd_force_geturl }}
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: set permissions on ipmitool.sh
    file: path=/usr/local/bin/ipmitool.sh owner=nobody group=nobody mode=0755
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: add sudoers rule for ipmitool
    template: src=sudo_collectd_ipmitool dest=/etc/sudoers.d/sudo_collectd_ipmitool owner=root group=root mode=0640
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: install ipmitool if virtualization role is not guest
    yum: name=ipmitool state=present
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: install dcmi.sh on non guest hosts
    get_url: owner=nobody group=nobody mode=0755 backup=no 
             url=https://raw.githubusercontent.com/jabl/collectd-plugin-dcmi/v2.0.0/dcmi.sh 
             dest=/usr/local/sbin/dcmi.sh
             force={{ collectd_force_geturl }}
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: add sudoers rule for freeipmi
    template: src=sudo_collectd_freeipmi dest=/etc/sudoers.d/sudo_collectd_freeipmi owner=root group=root mode=0640
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: install freeipmi if virtualization role is not guest
    yum: name=freeipmi state=present
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: drop some collectd excessive message by rsyslog
    template: src=collectd_rsyslog_drop.conf dest=/etc/rsyslog.d/10_collectd_drop.conf owner=root mode=0644 backup=no
    register: collectd_rsyslog_drop
    when: ansible_virtualization_role != "guest" and collectd_ipmitool

  - name: enable and start collectd
    service: name=collectd state=started enabled=yes

  - name: restart rsyslog if collectd_rsyslog_drop changed
    service: name=rsyslog state=restarted
    when: collectd_rsyslog_drop.changed

  - name: restart collectd on configchange
    service: name=collectd state=restarted
    when: collectd_config.changed
