---

- name: reload_collectd
  service:
   name: collectd
   state: reloaded

- name: restart_collectd
  service:
   name: collectd
   state: restarted
   enabled: true

- name: restart_rsyslog
  service:
    name: rsyslog
    state: restarted
